name: pre-commit checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

env:
  GO_VERSION: '^1.19'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: pre-commit/action@v3.0.0